### ISSUE TITLE
Transaction not getting executed

### ISSUE THREAD

**Issue by Tejas-Teju** [raydium-io/raydium-frontend#2]
I am trying to run raydium v2 code on my local on devnet
I have made my own market_id for two test tokens on devnet using serum dex

When I try to create a liquidity pool for the market_id, all I can see is this following message
![Raydium alert](https://user-images.githubusercontent.com/34937107/162147532-3baa9fb0-caab-4cf6-a08b-bf252a1c61ee.png)
** Taddaaaa is a text that I have added while debugging not something that was already present in the repo 
Nothing happens after this and no transaction gets subscribed to or completed or not even any fail requests.
Can somebody help out as to how to go ahead with this

**Comment by edsolater** [comment]
has fixed

**Comment by edsolater** [comment]
create liuidity used to has Bug. Congratulations, for finding it.

**Comment by alpha-defi** [comment]
@Tejas-Teju Were you able to successfully use the raydium-frontend on devnet? If so, what were the steps you took for devnet to work?

To my understanding, I think it requires the following:

1. Update the program ids in raydium-sdk 
2. Update the raydium-sdk devnet tokens
